### ISSUE TITLE
Warnings

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-search#20]
Sammlung .
Fix ich selbst in DEV-Branch.

Notice: Undefined position: args in ...rrze-search/src/RRZESearch/Infrastructure/Persistence/SettingsAPI.php on line 131

Notice: Undefined index: args in ..rrze-search/src/RRZESearch/Infrastructure/Templates/admin-engine-configuration.php on line 53

Für Entwicklung/Abnahme/Test wird natürlich der DEBUGMODE eingeschaltet.

**Comment by xwolfde** [comment]
Auf dem Frontend:

Notice: Undefined index: args in /var/www/vhosts/wordpress/websource/wp-content/plugins/rrze-search/src/RRZESearch/Application/Widget/SearchWidget.php on line 210
Webauftritt durchsuchen
Geben Sie hier den Suchbegriff ein, um in diesem Webauftritt zu suchen:

Notice
: Undefined index: s in
/var/www/vhosts/wordpress/websource/wp-content/plugins/rrze-search/src/RRZESearch/Infrastructure/Templates/widget.php
on line
58

**Comment by xwolfde** [comment]
fixed in dev.

**Comment by xwolfde** [comment]
Wenn die Suchseite ohne Parameter aufgerufen wird:
```
Notice: Undefined index: q in /var/www/vhosts/wordpress/websource/wp-content/plugins/rrze-search/src/RRZESearch/Application/Shortcode/ResultsShortcode.php on line 45

Notice: Undefined index: se in /var/www/vhosts/wordpress/websource/wp-content/plugins/rrze-search/src/RRZESearch/Application/Shortcode/ResultsShortcode.php on line 47

Notice: Undefined index: in /var/www/vhosts/wordpress/websource/wp-content/plugins/rrze-search/src/RRZESearch/Application/Shortcode/ResultsShortcode.php on line 47

Fatal error: Uncaught Error: Class name must be a valid object or a string in /var/www/vhosts/wordpress/websource/wp-content/plugins/rrze-search/src/RRZESearch/Application/Shortcode/ResultsShortcode.php:52 Stack trace: #0 /var/www/vhosts/wordpress/websource/wp-includes/shortcodes.php(319): RRZE\RRZESearch\Application\Shortcode\ResultsShortcode->shortcodeInit('', '', 'rrze_search_res...') #1 [internal function]: do_shortcode_tag(Array) #2 /var/www/vhosts/wordpress/websource/wp-includes/shortcodes.php(197): preg_replace_callback('/\\[(\\[?)(rrze_s...', 'do_shortcode_ta...', '[rrze_search_re...') #3 /var/www/vhosts/wordpress/websource/wp-includes/class-wp-hook.php(286): do_shortcode('[rrze_search_re...') #4 /var/www/vhosts/wordpress/websource/wp-includes/plugin.php(203): WP_Hook->apply_filters('[rrze_search_re...', Array) #5 /var/www/vhosts/wordpress/websource/wp-includes/post-template.php(240): apply_filters('the_content', '[rrze_search_re...') #6 /var/www/vhosts/wordpress/websource/wp-content/themes/FAU-Einrichtungen/page. in /var/www/vhosts/wordpress/websource/wp-content/plugins/rrze-search/src/RRZESearch/Application/Shortcode/ResultsShortcode.php on line 52
```

**Comment by xwolfde** [comment]
Ich übernehme erstmal

**Comment by xwolfde** [comment]
*COUCH*

  $resource     = $this->options['rrze_search_resources'][$_GET['se']];   

Lets hack this site.
Sanitize everything coming from the net.  First session, first rule in every class for web programming.

**Comment by xwolfde** [comment]
Sehe derzeit keine Warnings mehr
