### ISSUE TITLE
Viele Fehler bei Suchausführung

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-search#26]
Liegt das an meinen Testserver oder am Plugin?

```
Notice: Use of undefined constant CURLOPT_HTTPHEADER - assumed 'CURLOPT_HTTPHEADER' in /var/www/vhosts/wordpress/websource/wp-content/plugins/rrze-search/src/RRZESearch/Infrastructure/Engines/Foundations/GoogleSearch.php on line 72

Notice: Use of undefined constant CURLOPT_HEADER - assumed 'CURLOPT_HEADER' in /var/www/vhosts/wordpress/websource/wp-content/plugins/rrze-search/src/RRZESearch/Infrastructure/Engines/Foundations/GoogleSearch.php on line 73

Notice: Use of undefined constant CURLOPT_URL - assumed 'CURLOPT_URL' in /var/www/vhosts/wordpress/websource/wp-content/plugins/rrze-search/src/RRZESearch/Infrastructure/Engines/Foundations/GoogleSearch.php on line 74

Notice: Use of undefined constant CURLOPT_SSL_VERIFYPEER - assumed 'CURLOPT_SSL_VERIFYPEER' in /var/www/vhosts/wordpress/websource/wp-content/plugins/rrze-search/src/RRZESearch/Infrastructure/Engines/Foundations/GoogleSearch.php on line 75

Notice: Use of undefined constant CURLOPT_SSL_VERIFYHOST - assumed 'CURLOPT_SSL_VERIFYHOST' in /var/www/vhosts/wordpress/websource/wp-content/plugins/rrze-search/src/RRZESearch/Infrastructure/Engines/Foundations/GoogleSearch.php on line 76

Notice: Use of undefined constant CURLOPT_RETURNTRANSFER - assumed 'CURLOPT_RETURNTRANSFER' in /var/www/vhosts/wordpress/websource/wp-content/plugins/rrze-search/src/RRZESearch/Infrastructure/Engines/Foundations/GoogleSearch.php on line 77

Notice: Use of undefined constant CURLOPT_TIMEOUT - assumed 'CURLOPT_TIMEOUT' in /var/www/vhosts/wordpress/websource/wp-content/plugins/rrze-search/src/RRZESearch/Infrastructure/Engines/Foundations/GoogleSearch.php on line 78

Notice: Use of undefined constant CURLOPT_CONNECTTIMEOUT - assumed 'CURLOPT_CONNECTTIMEOUT' in /var/www/vhosts/wordpress/websource/wp-content/plugins/rrze-search/src/RRZESearch/Infrastructure/Engines/Foundations/GoogleSearch.php on line 79

Notice: Use of undefined constant CURLOPT_HEADER - assumed 'CURLOPT_HEADER' in /var/www/vhosts/wordpress/websource/wp-content/plugins/rrze-search/src/RRZESearch/Infrastructure/Engines/Foundations/GoogleSearch.php on line 80

Notice: Use of undefined constant CURLOPT_FOLLOWLOCATION - assumed 'CURLOPT_FOLLOWLOCATION' in /var/www/vhosts/wordpress/websource/wp-content/plugins/rrze-search/src/RRZESearch/Infrastructure/Engines/Foundations/GoogleSearch.php on line 81

Fatal error: Uncaught Error: Call to undefined function RRZE\RRZESearch\Infrastructure\Engines\Foundations\curl_init() in /var/www/vhosts/wordpress/websource/wp-content/plugins/rrze-search/src/RRZESearch/Infrastructure/Engines/Foundations/GoogleSearch.php:85 Stack trace: #0 /var/www/vhosts/wordpress/websource/wp-content/plugins/rrze-search/src/RRZESearch/Application/Shortcode/ResultsShortcode.php(56): RRZE\RRZESearch\Infrastructure\Engines\Foundations\GoogleSearch->query('Hallo', Array, 1) #1 /var/www/vhosts/wordpress/websource/wp-includes/shortcodes.php(319): RRZE\RRZESearch\Application\Shortcode\ResultsShortcode->shortcodeInit('', '', 'rrze_search_res...') #2 [internal function]: do_shortcode_tag(Array) #3 /var/www/vhosts/wordpress/websource/wp-includes/shortcodes.php(197): preg_replace_callback('/\\[(\\[?)(rrze_s...', 'do_shortcode_ta...', '[rrze_search_re...') #4 /var/www/vhosts/wordpress/websource/wp-includes/class-wp-hook.php(286): do_shortcode('[rrze_search_re...') #5 /var/www/vhosts/wordpress/websource/wp-includes in /var/www/vhosts/wordpress/websource/wp-content/plugins/rrze-search/src/RRZESearch/Infrastructure/Engines/Foundations/GoogleSearch.php on line 85
```

**Comment by jkphl** [comment]
@xwolfde Möglich, dass kein cURL zur Verfügung steht? Das sind alles Warnungen, dass cURL-Konstanten nicht existieren würden. Sollte eigentlich nicht der Fall sein, wenn cURL ordentlich verfügbar ist ...

**Comment by xwolfde** [comment]
Strange. Sollte eigentlich da sein. Und letztes mal ging es ja. Ich upgrade mal den Server.

**Comment by xwolfde** [comment]
ok, ja, das wars...  Beim upgrade auf 7.1 diese Lib vergessen . Mea culpa.

**Comment by jkphl** [comment]
Wollte gerade sagen: Im Notfall könnten wir auch auf eine `file_get_contents()` alternative ausweichen (ggf. auch als Fallback)
